version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mini-toolbox-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # 持久化存储上传和压缩的文件
      - uploads_data:/app/uploads
      - compressed_data:/app/compressed
    environment:
      - GIN_MODE=release
      - TZ=Asia/Shanghai
    networks:
      - mini-toolbox-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mini-toolbox-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - mini-toolbox-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

# 数据卷
volumes:
  uploads_data:
    driver: local
  compressed_data:
    driver: local

# 网络
networks:
  mini-toolbox-network:
    driver: bridge